<<<<<<< HEAD
import pytest

if __name__ == '__main__':
  print('EX00')
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex00.py'])
  print('EX01')
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex01.py'])
  print('EX02')
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex02.py'])
  print('EX03')
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex03.py'])
  print('EX04')
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex04.py'])
  print('EX05')
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex05.py'])
  print('EX06')
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex06.py'])
  print('EX07')
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex07.py'])
  print('EX09')
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex09.py'])
  print('EX10')
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex10.py'])
  print('EX11')
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex11.py'])
  print('EX12')
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex12.py'])
  print('EX13')
=======
import pytest

if __name__ == '__main__':
  print('EX00')
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex00.py'])
  print('EX01')
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex01.py'])
  print('EX02')
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex02.py'])
  print('EX03')
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex03.py'])
  print('EX04')
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex04.py'])
  print('EX05')
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex05.py'])
  print('EX06')
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex06.py'])
  print('EX07')
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex07.py'])
  print('EX09')
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex09.py'])
  print('EX10')
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex10.py'])
  print('EX11')
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex11.py'])
  print('EX12')
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex12.py'])
  print('EX13')
>>>>>>> 9ce1c2ba069d44b4668c5a68c79e72bffcb9943b
  pytest.main(['-v', '--tb=short', '--no-header', './.test/test_ex13.py'])